name: hexlet-ci-app
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - run: npm install
            - run: npm make setup
            - run: npm make test
            - run: npm make lint
